[build]
builder = "nixpacks"
buildCommand = """
    apt-get update && \
    apt-get install -y python3.11 python3-pip && \
    cd backend && \
    pip3 install --no-cache-dir -r requirements.txt && \
    pip3 install --no-cache-dir gunicorn
"""

[deploy]
startCommand = "cd backend && python3 -m gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
healthcheckPath = "/"
healthcheckTimeout = 200
restartPolicyType = "on_failure"
port = 8000

[nixpacks]
workdir = "backend"

[nixpacks.setup]
python_version = "3.11"
providers = ["python", "apt"] 