[build]
builder = "nixpacks"
buildCommand = "cd backend && python -m ensurepip && python -m pip install --upgrade pip && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
healthcheckPath = "/docs"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[nixpacks]
workdir = "backend"

[nixpacks.setup]
python_version = "3.11"
providers = ["python"] 